### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ollakalla** [sindresorhus/sublime-autoprefixer#69] opened 2016-05-07 10:13 UTC
I have install Autoprefixer from Package Controller as the documentation on windows machine
and make sure that i have node installed with version v5.3.0
but it is not working. when i use the shortcut ctrl+alt+x

**Comment by kevva** [comment] 2016-05-07 18:59
Does it work when using it from the command palette (Cmd+Shift+P)?

**Comment by sindresorhus** [comment] 2016-05-08 02:31
Probably a duplicate of https://github.com/sindresorhus/sublime-autoprefixer/issues/68#issuecomment-192837311.

**Closed by sindresorhus** 2016-05-08 02:31 UTC

**Comment by kevva** [comment] 2016-05-15 13:59
I thought he wasn't able to use it, not that he couldn't find it?

**Comment by sindresorhus** [comment] 2016-05-15 14:04
Oh, I linked to the wrong issue, but the deal is that he probably tried to autoprefix something that didn't need prefixing and nothing happened.

**Comment by kevva** [comment] 2016-05-15 14:08
Probably, yeah.

**Comment by ollakalla** [comment] 2016-05-15 14:15
i try box-shadow but didn't work

**Comment by kevva** [comment] 2016-05-15 15:50
`box-shadow` doesn't need prefixing.

**Comment by ollakalla** [comment] 2016-05-15 16:02
Could you give me something to test :D

**Comment by kevva** [comment] 2016-05-15 16:32
Try `flex: 0 0 100%`.
